DROP TABLE IF EXISTS RATE;
DROP TABLE IF EXISTS VOTE;
DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS vacancy;
DROP TABLE IF EXISTS FRESHEN_GOAL;
DROP TABLE IF EXISTS FRESHEN;
DROP TABLE IF EXISTS EMPLOYER;
DROP TABLE IF EXISTS USERS;
DROP SEQUENCE IF EXISTS GLOBAL_SEQ;

CREATE SEQUENCE GLOBAL_SEQ START WITH 100000 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS USERS
(
    ID INTEGER DEFAULT NEXTVAL('GLOBAL_SEQ') PRIMARY KEY NOT NULL,
    NAME                  VARCHAR(255)             NOT NULL,
    EMAIL                 VARCHAR(255)             NOT NULL,
    PASSWORD              VARCHAR(255)             NOT NULL,
    REGISTERED            TIMESTAMP DEFAULT NOW(),
    ENABLED               BOOLEAN   DEFAULT TRUE
);
CREATE UNIQUE INDEX IF NOT EXISTS USERS_UNIQUE_EMAIL_IDX ON USERS (EMAIL);

CREATE TABLE IF NOT EXISTS USER_ROLES
(
    USER_ID                INTEGER NOT NULL,
    ROLE                   VARCHAR(255),
    CONSTRAINT USER_ROLES_IDX UNIQUE (USER_ID, ROLE),
    FOREIGN KEY (USER_ID) REFERENCES users (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EMPLOYER
(
    ID INTEGER DEFAULT NEXTVAL('GLOBAL_SEQ') PRIMARY KEY NOT NULL,
    NAME                   VARCHAR(255)            NOT NULL,
    ADDRESS                VARCHAR(255)            NOT NULL,
    CONSTRAINT EMPLOYER_IDX UNIQUE (NAME, ADDRESS)
);

CREATE TABLE IF NOT EXISTS FRESHEN
(
    ID INTEGER DEFAULT NEXTVAL('GLOBAL_SEQ') PRIMARY KEY NOT NULL,
    RECORDED_DATE         TIMESTAMP  DEFAULT NOW() NOT NULL,
    LANGUAGE              VARCHAR(255)             NOT NULL,
    LEVEL                 VARCHAR(255)             NOT NULL,
    WORKPLACE             VARCHAR(255)             NOT NULL,
    USER_ID               INTEGER,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FRESHEN_GOAL
(
    FRESHEN_ID             INTEGER NOT NULL,
    GOAL                   VARCHAR(255),
    FOREIGN KEY (FRESHEN_ID) REFERENCES FRESHEN (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VACANCY
(
    ID INTEGER DEFAULT NEXTVAL('GLOBAL_SEQ') PRIMARY KEY NOT NULL,
    TITLE                 VARCHAR(255)             NOT NULL,
    SALARY_MIN            INTEGER                  NOT NULL,
    SALARY_MAX            INTEGER                  NOT NULL,
    LINK                  VARCHAR(255)             NOT NULL,
    SKILLS                VARCHAR(255)             NOT NULL,
    RELEASE_DATE          DATE                     NOT NULL,
    EMPLOYER_ID           INTEGER                  NOT NULL,
    FRESHEN_ID            INTEGER                  NOT NULL,
    CONSTRAINT VACANCY_IDX UNIQUE (TITLE, SKILLS, EMPLOYER_ID),
    FOREIGN KEY (EMPLOYER_ID) REFERENCES EMPLOYER (ID) ON DELETE CASCADE,
    FOREIGN KEY (FRESHEN_ID)  REFERENCES FRESHEN (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VOTE
(
    ID INTEGER DEFAULT NEXTVAL('GLOBAL_SEQ') PRIMARY KEY NOT NULL,
    DATE_VOTE            DATE                     NOT NULL,
    VACANCY_ID            INTEGER                  NOT NULL,
    USER_ID               INTEGER                  NOT NULL,
    CONSTRAINT VOTES_IDX UNIQUE (VACANCY_ID, USER_ID),
    FOREIGN KEY (VACANCY_ID) REFERENCES VACANCY (ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RATE
(
    ID INTEGER DEFAULT NEXTVAL('GLOBAL_SEQ') PRIMARY KEY NOT NULL,
    NAME                  VARCHAR(255)             NOT NULL,
    VALUE_RATE            DOUBLE                   NOT NULL,
    DATE_RATE             DATE                     NOT NULL,
    CONSTRAINT RATE_IDX UNIQUE (NAME)
);

